site_name: 404 - A Privacy Tool
site_url: https://un-nf.github.io/404-docs/
repo_url: https://github.com/un-nf/404

nav: 
  - Home: index.md
  - Overview:
    - What is 404?: Overview/whatIs.md
    - Why do I need 404?: Overview/why404.md
    - Quick Consent & Warning: Overview/consent.md
  - Getting Started:
    - App (alpha): getStart/appStart.md
  - Developer Resources:
    - Repository (Github/Codeberg): dev/repoDev.md
    - Download: dev/downloadDev.md
    - Dependencies: dev/depsDev.md
    - Get Started: dev/repoStart.md
    - eBPF Guide: dev/ebpf.md
  - FAQ: faq.md

theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy

markdown_extensions:

#emojis & icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Mermaid support
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - admonition

# !!! (???)
#    TEXT HERE

  - attr_list

# BUTTON
#     [Subscribe to our newsletter](#){ .md-button }

# Primary
#     [Subscribe to our newsletter](#){ .md-button .md-button--primary }

# w/ icon
#     [Send :fontawesome-solid-paper-plane:](#){ .md-button }

  - pymdownx.details # for admonition
  - pymdownx.superfences # for admonition + code highlighting
  - pymdownx.inlinehilite # for code highlighting
  - pymdownx.snippets # for code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
